### ISSUE TITLE
URGENT - Reservations between 22 UT and 00 UT remains unavailable

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/reservations-interface#11]
URGENT - Reservations between 22 UT and 00 UT remains unavailable

I tried to access last night in order to record a videotutorial as well as to test the night telescopes. But I was not able to make any reservation in that interval.

At this stage of the project is essential that telescope testers have the maximum time available to test (instead of having to wait until 2 am (local hour) to start a test).

**Comment by fserena** [comment]
Yes they should be available, but not in time. I mean, you can make a reservation right now for tonight between 22 and 00 UT. Anyway, it must work in any case as soon as possible.

**Comment by fserena** [comment]
Hopefully fixed. Need to test it tonight. I keep this issue open until then.

**Comment by fserena** [comment]
It is working properly now.

**Comment by angelagonzalez** [comment]
It is not fixed yet
![sigue sin poder reservarse entre 22 y 0 ut a 26-04-2014](https://cloud.githubusercontent.com/assets/6812954/2812372/72a590d2-ce53-11e3-966b-5a768d697fde.jpg)
.

**Comment by fserena** [comment]
You had 26th of April selected, and you were on 25th of April (UT) at that time (UT+2). Why didn't you choose the correct day? :D

**Comment by angelagonzalez** [comment]
The date was 26th April and I selected day 26 on the calendar.
No user would select day 25th if it is day 26th.
Besides, the system leads you to the current local day automatically (26th in this case), as you can in the figure.
In addition, the first time shown in the reservation list is the local time, not the UT one.
GLORIA is supposed to be user friendly, not a joke that makes users give up. And of course, not a joke that makes testers miss time with this.

**Comment by angelagonzalez** [comment]
Fixed!
Thanks.
