### ISSUE TITLE
Experimento Nocturno del Proyecto Gloria

### ISSUE THREAD

**Issue by dailoscm** [GLORIA-project/reservations-interface#12]
Hola, 
Quisiera pedirles información (a quién sepa) sobre el Experimento Nocturno del Proyecto Gloria, ya que siempre que intento reservar hora me dice que no hay disponibles.

Un saludo y gracias.

**Comment by dailoscm** [comment]
How I can use the telescope at night? There is never available hours. Thank you.

**Comment by lnicastro** [comment]
Telescopes are not yet publicly accessible. Let's see if you can be added to the list of testers. Somebody else of the team will reply. These are vacation days...

**Comment by dailoscm** [comment]
Alright, thank you very  much. I will be waiting for your news.

**Comment by esgg** [comment]
Buenos días.

De momento, el experimento nocturno se encuentra en fase de pruebas. Aunque puedas ver los horarios, no se te permite reservar a no ser que seas una de las personas encargadas de los tests. Esperamos abrir pronto.

Gracias por tu interés y perdona por la tardanza en la respuesta.

GLORIA team

**Comment by dailoscm** [comment]
De acuerdo, gracias por la respuesta, pero solo una pregunta más, ¿existe alguna posibilidad de participar en los test?

Un saludo y gracias.

**Comment by esgg** [comment]
Tengo que consultarlo con nuestro jefe de proyecto. Te contesto lo antes posible.

**Comment by dailoscm** [comment]
Muchas gracias por las molestias.

**Comment by esgg** [comment]
Buenos días.

Hemos abierto el experimento nocturno en modo "prueba" de 21:00 UT a 22:00 UT. Esperamos que puedes disfrutar de una bonita experiencia. No dudes en mandarnos cualquier comentario.

GLORIA team

**Comment by dailoscm** [comment]
¡¡Muchas gracias!! Vivo en un piso de estudiantes e intentaremos disfrutar todos de la experiencia. 

Un saludo e insisto, gracias!

**Comment by dailoscm** [comment]
Hola "esgg" he intentado usar el TADn y me ha dado problemas, tanto ayer como hoy. 
El primer problema es que en donde supongo que debe verse lo que observa el telescopio (imagen central), se ve una especie de imagen predeterminada. Luego he puesto las coordenadas celestiales en las que se apreciaba Saturno (desde Tenerife), basándome en los datos obtenidos de las efemérides del OAN (Observatorio Astronómico Nacional), seleccionaba Saturno en la pestaña de objetos y por último le daba a la diana para mover el telescopio y aún así me seguía saliendo la foto predeterminada. Con lo que probé a sacar videos y fotos y se veía como la lluvia de la televisión analógica (es decir ruido blanco).

Perdona por todo el relato anterior, pero ya que hacemos pruebas, pensé que era interesante comentarlo y así aprovecho para ver si me dice el posible error que he cometido, con tal de corregirlo para la hora que tengo para mañana viernes 9. 

Un saludo y gracias por la atención,
dailoscm

**Comment by esgg** [comment]
Antes de nada muchas gracias por los comentarios. Nos ayuda mucho a mejorar.

El proceso para realizar observaciones es:
  --> Introducir las coordenadas o el nombre del objeto
 --> Mover la montura
 --> Realizar exposiciones

¿La imágen salía totalmente en blanco? Cuando la imagen sale alta puede ser debido a que el tiempo de exposición era muy alto. ¿Te acuerdas de cuanto pusiste?

Si la imagen salía con alguna raya es posible que no haya apuntado bien. ¿Te fijaste si se movió la montura?

Saludos y perdona por las molestias.
