### ISSUE TITLE
Problemas con la reserva

### ISSUE THREAD

**Issue by nchazarra** [GLORIA-project/reservations-interface#13]
Estimados Srs.,

Desde hace uno o dos meses llevo intentando hacer reservas en alguno de los telescopios para tomar imágenes durante la noche de algunos objetivos, pero me dice que no hay horas disponibles, y mi pregunta es, ¿Es debido a que está en uso o que no estoy autorizado para usarlos?. Gracias.

**Comment by esgg** [comment]
Buenos días,

es debido a que no está autorizado a usarlos, están en fase de pruebas. Probablemente se abran esta semana para su uso en modo test. Le avisaré en cuanto se produzca este hecho.

Gracias por el interes y disculpe las molestias.

GLORIA team

**Comment by nchazarra** [comment]
Muchas gracias por la información :)

¡Un saludo!

Enviado con MailTrackhttps://mailtrack.io/install?source=signature&lang=es&referral=nchazarra@gmail.com&idSignature=23

2014-05-05 14:06 GMT+01:00 esgg notifications@github.com:

> Buenos días,
> 
> es debido a que no está autorizado a usarlos, están en fase de pruebas.
> Probablemente se abran esta semana para su uso en modo test. Le avisaré en
> cuanto se produzca este hecho.
> 
> Gracias por el interes y disculpe las molestias.
> 
> GLORIA team
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GLORIA-project/reservations-interface/issues/13#issuecomment-42185291
> .

## 

Nahúm Méndez Chazarra
Estudiante de Geología | Universidad de Granada
nchazarra@gmail.com | Blog: http://www.ungeologoenapuros.es
Twitter: http://twitter.com/nchazarra | LinkedIn:
http://linkedin.com/in/nchazarra

**Comment by esgg** [comment]
Buenos días,

hemos abierto el experimento nocturno a los usuarios en modo "prueba". La disponibilidad es de 21:00 UT a 22:00 UT. No dudes en mandarnos cualquier comentario.

GLORIA Team
