### ISSUE TITLE
Cambiar encuesta final

### ISSUE THREAD

**Issue by carlibiri** [GLORIA-project/reservations-interface#15]
Prioridad: Muy alta

Se debería cambiar la encuesta final por éstas:

La de nuestra encuesta en Inglés (para insertarla al final del Experimento
Nocturno):

https://docs.google.com/forms/d/1zFZexlvF_otlNyMCZDKXa84Ga8iodXjRm0MxLLuARlM/viewform

La encuesta en Español (también para insertarla):

https://docs.google.com/forms/d/1ys1b8EiC8COj8oBQtFQWuCE3f_J1ljZUojpVGm0TOUk/viewform

La que hay actualmente la creó Filip, y sólo él tiene acceso. Creemos que sería mejor que se pusieran éstas.

**Comment by angelagonzalez** [comment]
Ok, se han incluido los dos enlaces. Pero se ven muy poco, casi pasan inadvertidos. ¿Es posible resaltarlos y hacerlos mucho más grandeS? Gracias.

**Comment by fserena** [comment]
Esteban, ¿puedes trasferir esta incidencia al repositorio de experimento nocturno?

**Comment by fserena** [comment]
https://github.com/GLORIA-project/night-experiment-interface/issues/6

**Comment by esgg** [comment]
Ampliados los textos.

**Comment by angelagonzalez** [comment]
Ok, right but, in order to see it better,

is it possible to put the sentences a little lower, in orange color and in capital letters as in the example (snapshot)? Thanks.

![12-06-2014 realzar encuesta](https://cloud.githubusercontent.com/assets/6812954/3261786/f540eef0-f25d-11e3-8371-3a8e11623cf5.jpg)

**Comment by esgg** [comment]
Cambiado

**Comment by angelagonzalez** [comment]
Probado en pre-producción y la apariencia OK pero:

1) Cuando la reserva llega a 00:00 la interfaz se queda como "congelada" y tarda mucho en cambiarse la pantalla y aparecer la encuesta.

2) Al pinchar en "HERE" aparece rápidamente la encuesta en Inglés, pero al pinchar en "AQUÍ" la pestaña nueva del navegador se queda como pensando y tarda bastante.

Quizá se debe a la "hora punta" en que todos los usuarios quieren rellenar la encuesta a la vez.

Ya no sé si esto se produce porque estaba dentro de la reserva de otro usuario y además en pre-producción o si no tiene nada que ver.

**Comment by esgg** [comment]
En principio lo de la encuesta no tiene nada que ver. Tanto la versión inglesa como española son enlaces a una página de google. No creo que fuera por el tema de la "hora punta".

**Comment by angelagonzalez** [comment]
Me acabo de dar cuenta de que si durante la reserva salta el aviso de que quedan 2 minutos y no lo cierras, la interfaz del experimento se queda colgada y tarda un rato grande en expulsar al usuario. 

Cuando después aparecen los enlaces a las reservas, al pincharles, no funciona ninguno (se queda colgada la nueva pestaña que se intenta abrir, sin conducir a ninguna parte (about:blank)).

Después de pinchar varias veces en los links de las encuestas, finalmente sí las abre en una nueva pestaña, pero antes de eso hay que abrir 2 o 3 pestañas "fallidas" que se quedan abiertas en blanco sin hacer nada.

**Comment by esgg** [comment]
Estoy intentando reproducir el error pero no lo consigo. ¿Qué navegador estás usando?

**Comment by angelagonzalez** [comment]
Firefox 30.

**Comment by esgg** [comment]
¿Estás usando la versión de Windows o Linux?

**Comment by angelagonzalez** [comment]
Windows.

**Comment by esgg** [comment]
Me he instalado la version 30 pero sigo sin reproducir el error. Cuando no se cierra el mensaje, es normal que la primera vez no funcione el enlace. Con ese primer click, se deshabilita el sombreado del mensaje. Lo raro es que no se vaya tras el primer click.

Por favor, podrías volver a repetir el proceso para intentar descartar otro tipo de errores. Gracias

**Comment by angelagonzalez** [comment]
Lo repetí tres veces anoche y también ocurrió cuando lo probé en pre-producción.

Se trata de que si por algún motivo no se le da a cerrar el aviso de que quedan dos minutos (por ejemplo porque el usuario se ha despistado haciendo otra cosa, o le han llamado por teléfono, o no le funciona nada y está esperando a que acabe la reserva para rellenar la encuesta, etc), si se termina el tiempo de reserva y el usuario no quitó el mensaje, se queda todo como congelado en lugar de expulsar al usuario de la reserva. Y cuando el usuario se da cuenta y cierra el mensaje de los 2 minutos, se sigue quedando congelado durante varios minutos más antes de que se expulse al usuario y aparezca la pantalla con los links de la encuesta.

Para entonces lo más probable es que el usuario piense que el sistema se ha quedado colgado y cierre el navegador sin poder rellenar la encuesta.

**Comment by angelagonzalez** [comment]
Hola. Por favor, que alguien reabra esta incidencia porque todavía está dando coletazos.

Anoche (10-07-2014) le ocurrió a ACT quedarse el sistema congelado en 00 tras usar B-1A (no así tras usar B-2 al parecer). Se trata de la reserva: 6484.

Testimonio textual: " A diferencia de B2, no sale la encuesta rápidamente como en B2 y se queda la pantalla congelada en 00:00 . ¿Tal vez por haber mandado el telescopio a una posición no accesible (M1) al final? He tenido que hacer log out y ya se acabó".

**Comment by esgg** [comment]
He estado comprobando los logs. 

Efectivamente se apuntó a un target por debajo del horizonte pero eso no influye en el remaining time.

Se realizó una llamada al sistema de control de tiempo un minuto y medio antes.  Esto es normal, pero lo que no es normal es que no se hicieran más. Parece como si fallara el timer pero no entiendo por qué pasa en unos navegadores y telescopios determinados.
