### ISSUE TITLE
La encuesta final no se ve bien en Firefox

### ISSUE THREAD

**Issue by carlibiri** [GLORIA-project/reservations-interface#16]
Prioridad: Alta

Parece que la encuesta final no se muestra correctamente, quizás sería mejor que esta encuesta se abriera en una nueva ventana. Parece que se está mentiendo en un frame y el Firefox no se lo traga correctamente.

![la encuesta sale rara 13-05-2014](https://cloud.githubusercontent.com/assets/7371595/3011750/c179470c-df2f-11e3-9324-536317c6ecf6.jpg)

**Comment by fserena** [comment]
Esteban, esta incidencia corresponde a la interfaz del experimento nocturno. ¿Podrías trasferirla?

**Comment by carlibiri** [comment]
Ayer realicé observación y aunque me invitaba a rellenar la encuesta, no me aparecía...

**Comment by fserena** [comment]
Cierro esta issue porque se está siguiendo en https://github.com/GLORIA-project/night-experiment-interface/issues/6
