### ISSUE TITLE
Eliminar el icono de obras

### ISSUE THREAD

**Issue by carlibiri** [GLORIA-project/reservations-interface#18]
Prioridad: Media

Parece que este icono da problemas en el interfaz y no creemos que sea necesario. Mejor que los usaurios reporten los errores por las encuestas y Ángela se dedicará a anotar las incidencias en Github.

**Comment by fserena** [comment]
Este icono sólo aparece en el experimento nocturno. Por favor Esteban, mueve esta incidencia allí.
