### ISSUE TITLE
Eliminar usuarios antiguos de GLORIA

### ISSUE THREAD

**Issue by carlibiri** [GLORIA-project/reservations-interface#19]
Prioridad: Alta

Eliminar los usuarios antiguos para que puedan volver a acceder, parece que ahora no pueden acceder.

**Comment by fserena** [comment]
Lo que ocurre es que hay bastantes usuarios de GLORIA que se registraron en Liferay cuando los servicios estaban alojados en una de las máquinas de nuestro laboratorio en la UPM. Estas máquinas estuvieron caídas intermitentemente durante varias semanas por cortes de luz. Si alguien se daba de alta en GLORIA (Liferay) en ese momento, los servicios no se "enteraban" y el nuevo usuario se quedaba "huérfano", aunque él recibiese un OK.

Lo que tenemos que hacer es identificar el subconjunto que está en Liferay y no en GLORIA y, si os parece bien, enviarles un correo de reseteo de cuenta.

**Comment by carlibiri** [comment]
Me parece bien...

**Comment by fserena** [comment]
Movida al repositorio correcto
