### ISSUE TITLE
Coherencia en el estado actual el campo "Tiempo"

### ISSUE THREAD

**Issue by carlibiri** [GLORIA-project/reservations-interface#20]
Prioridad: alta

Hemos comprobado que en algunas ocasiones, cuando el tiempo es malo, esto no aparece en el menú de acceso a las reservas. Creo que la mejor opción sería quitar este campo por ahora.

Os adjunto captura de pantalla.
![10-05-2014 informacin incorrecta al usuario b-3](https://cloud.githubusercontent.com/assets/7371595/3011808/bf550f32-df30-11e3-89e8-6ad770115a5e.jpg)

**Comment by fserena** [comment]
Estuvimos hablando con MªCarmen para dar una solución a esta incoherencia. Ahora mismo se decide mostrar CLEAR si no hay alarma de viento ni de humedad. Lo que pensamos es iterar por todos los dispositivos de tiempo atmosférico y si alguno de ellos está en alarma mostrarla.

**Comment by angelagonzalez** [comment]
Esta incidencia está relacionada con ésta: https://github.com/GLORIA-project/GLORIA_RTSInteractiveRTS2/issues/11

**Comment by angelagonzalez** [comment]
Apart from showing correctly the weather, is extremely important to inform the user when 'GRB on going', for example last night (6 Jun 2014) in BOOTES-2.

The users could not access their reservations due to a GRB but the message that appeared was 'Problem in telescope', so they thought it was a GLORIA bug.

**Comment by fserena** [comment]
Angela, the issue you are referring is in https://github.com/GLORIA-project/gloria-soap/issues/8

**Comment by fserena** [comment]
Carlos, he cerrado esta issue porque ya se implementó la solución que describí unos comentarios antes. Está funcionando sin problemas.
