### ISSUE TITLE
D50 no tiene cúpula

### ISSUE THREAD

**Issue by esgg** [GLORIA-project/reservations-interface#21]
El telescopio  D50 no tiene cúpula por lo que devuelve ERROR. Se podría mostrar como estado UNKNOWN o UNDEFINED para que no lleve a la confusión al usuario [Prioridad baja]

**Comment by alcoya** [comment]
En la sesión del jueves me ha sido imposible conectar. Siempre el mismo cuadro de diálogo. 
![d50_sesion_22_05_14_2](https://cloud.githubusercontent.com/assets/7673786/3060877/c01dcc32-e1fc-11e3-8fb6-7b03f66d4824.PNG)

**Comment by fserena** [comment]
Desde la semana pasada, el estado de la cúpula de D50 siempre es UNDEFINED.
