### ISSUE TITLE
Web de GLORIA inestable y no permite login - Estados de telescopios contradictorios

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/reservations-interface#22]
(Prioridad Alta)

La web de GLORIA se cuelga a ratos esta noche y a veces es imposible volver a loguearse con: Chrome, Firefox o I.Explorer.

Los estados de los telescopios son contradictorios: aparece la flecha naranja y acto seguido la llave inglesa roja, otra vez la naranja, etc. Los mensajes de estado de los telescopios tardan en aparecer y son cambiantes.

Es posible que los usuarios no estén pudiendo entrar hoy a GLORIA para usar sus reservas.

**Comment by fserena** [comment]
Para resolver esta incidencia nos pusimos en contacto con el proveedor de hosting de GLORIA. Aún se está investigando la razón del problema, pero tras un reinicio general parece que se recuperó la estabilidad.

**Comment by fserena** [comment]
Ángela, ¿te parece bien que cerremos esta incidencia? Cuando finalmente tengamos una conclusión de porqué sucedió contestaré aquí mismo para que todos podamos saberlo.

**Comment by angelagonzalez** [comment]
Afirmativo. Creo que se puede cerrar por ahora, sí. Aunque los usuarios reportaron problemas con la web en los dos días siguientes, creo que ahora ya va bien.
