### ISSUE TITLE
No puedo conectar con Bootes-2 (Problema en el Telescopio)

### ISSUE THREAD

**Issue by carlibiri** [GLORIA-project/reservations-interface#23]
Al intentar conectar, aparece problema en el telescopio. A ver qué ocurre?

Un saludo.

![image](https://cloud.githubusercontent.com/assets/7371595/3124293/496c2604-e77b-11e3-87eb-ac38c6fbbdf2.png)

**Comment by fserena** [comment]
Hubo una reserva anterior que en principio no generó problemas:

21:35:33.311 INFO  - {"name":"notify teleoperation","rt":"BOOTES-2","seconds":900,"sender":"teleoperation","client":"experiment"}

Tu reserva empezó mal, GLORIA recibía una excepción de servicio web (error interno de RTI o problema de conexión):

21:46:12.905 ERROR - {"name":"GenericTeleoperation","rt":"BOOTES-2","seconds":900,"message":"**Could not send Message.**","operation":"start","error":"**WebServiceException**","while":"after stop","sender":"teleoperation","client":"experiment"}

21:47:22.463 ERROR - {"name":"GenericTeleoperation","rt":"BOOTES-2","seconds":900,"message":"**Could not send Message**.","operation":"start","while":"**get executor state**","error":"**WebServiceException**","sender":"teleoperation","client":"experiment"}

Y ya estuvo así en adelante durante todas las reservas restantes:

22:30:24.613 ERROR - {"name":"GenericTeleoperation","rt":"BOOTES-2","seconds":900,"message":"Could not send Message.","operation":"start","while":"get executor state","error":"WebServiceException","sender":"teleoperation","client":"experiment"}

Las dos últimas trazas muestran que se lanzaba la excepción cuando se intentaba leer el estado del ejecutor.

**Comment by fserena** [comment]
Pienso que debe ser un error interno más que un problema de conexión, ya que el RTI sí que devolvía valores de estado de dispositivos (en tu captura).

**Comment by carlibiri** [comment]
A qué te refieres con error interno? Error del interfaz web? o de RTS2? Confirmame para notificarlo a la gente del CSIC o no.

Muchas gracias

**Comment by fserena** [comment]
Esas trazas se generan por la comunicación entre GLORIA (servicios, no web) y el RTI de BOOTES-2. Yo creo que el problema está entre el RTI y RTS2. No quiero hablar sin saber, pero creo que hay algo del ejecutor de RTS2 que hizo fallar a lo bestia (WebServiceException) al RTI.

De cualquier forma, pienso que lo más recomendable es blindar el RTI ante **cualquier** fallo en el enlace con RTS2.

**Comment by mclopez-uma** [comment]
Lo que ha pasado es que el EXEC de RTS2 se cayó, dejando abiertos dos puertos que enlazaban con el RTI. Hasta que no se han reiniciado varios módulos de RTS2 hace un momento, no se han liberado los puertos y el RTI no ha vuelto a funcionar correctamente.

**Comment by fserena** [comment]
Cierro esta issue porque ya se conoce el motivo del problema y está resuelto.
