### ISSUE TITLE
Permitir cancelar la reserva actual cuando el telescopio da fallo para poder reservar otra

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/reservations-interface#24]
Permitir que el usuario pueda cancelar una reserva cuando le sale la llave inglesa de problema el telescopio, para que pueda reservar en otro.

Actualmente se pueden cancelar con el aspa roja, pero no la reserva actual, por ejemplo cuando aparece la llave inglesa. Cuando esto ocurre, ni el usuario ni el administrador pueden cancelar la reserva para elegir otra.

Como está limitado a 2 reservas por usuario incluso siendo administrador, si coinciden las dos a la vez, el usuario pierde su tramo sin poder elegir otro, y el tester tiene que esperar a que finalicen los 15 minutos para poder elegir otra reserva y seguir probando.

**Comment by fserena** [comment]
Lo apunto para implementarlo con los arreglos y mejoras de esta semana.

**Comment by fserena** [comment]
GLORIA permite ahora cancelar una reserva cuando está en ERROR (llavecita inglesa). Para cancelar, hay que hacer click en el botón naranja.

**Comment by fserena** [comment]
Cuando probéis esta nueva funcionalidad y estéis conformes, se podrá cerrar esta issue.

**Comment by angelagonzalez** [comment]
Lamentablemente no está resuelto. Probado ahora mismo reservando en BOOTES-1A, que no está operativo, y no aparece ningún icono para cancelar.

Probado en Firefox con la caché borrada y con Chrome con la caché sin borrar. Adjunto captura de pantalla.
![17-06-2014 las reservas fallidas no se pueden cancelar](https://cloud.githubusercontent.com/assets/6812954/3306831/656af9cc-f665-11e3-8a43-e0dac83f838d.jpg)

**Comment by angelagonzalez** [comment]
¿Cómo va esta issue?

**Comment by fserena** [comment]
Perdona Ángela, debí explicarme mal hace 8 días. El cambio estaba implementado entonces y permitía cancelar una reserva cuando aparece la llave inglesa en el botón rojo a la izquierda (dije botón naranja). Para cancelar, hay que hacer click en ese botón.

**Comment by angelagonzalez** [comment]
En la propia llave inglesa roja?

**Comment by fserena** [comment]
Si, eso es un botón. La idea inicial fue ponerlo para realizar operaciones relacionadas con reservas en error. Ahora lo que permite es cancelarla.

**Comment by angelagonzalez** [comment]
Ok  lo probaré.

**Comment by angelagonzalez** [comment]
Acabo de hablar con Alberto y me comenta que por favor se cambie el mensaje que aparece al pasar el ratón por encima de la llave inglesa roja, para que en vez de decir "Problema en telescopio" diga: "Problema en telescopio. Pulse aquí para cancelar la reserva".

**Comment by fserena** [comment]
Perfecto, lo cambio en un rato. Desde hace más de una semana ya no debería poner "Problema en telescopio"...ahora indica "Telescopio no disponible".

**Comment by angelagonzalez** [comment]
Vale, también sirve. Lo importante es que al final indique que pulsando ahí se puede cancelar la reserva, para que el usuario lo sepa. Gracias.

**Comment by carlibiri** [comment]
Buena observación!

**Comment by fserena** [comment]
Desplegado. Esta noche ya debería estar disponible para las reservas en ERROR.

**Comment by angelagonzalez** [comment]
Comprobado con BART y con BOOTES-1A. Todo OK. Si os parece, cerramos la issue.
