### ISSUE TITLE
Add a button with the links to a filters features website for each telescope

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/reservations-interface#25]
This issue comes from this one: https://github.com/esgg/GLORIANightExperiment/issues/37

Add these links next to the list of filters for each telescope (see example on the attached snapshot):

LINKS:
- BART:

JOHNSON B: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=Generic/Johnson.B&&mode=browse&gname=Generic&gname2=Johnson#filter
JOHNSON V: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=Generic/Johnson.V&&mode=browse&gname=Generic&gname2=Johnson#filter
JOHNSON R: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=Generic/Johnson.R&&mode=browse&gname=Generic&gname2=Johnson#filter
z"(RG850): similar a: http://svo2.cab.inta-csic.es/theory/fps/index.php?id=KPNO/KP4in.Gunn_z&&mode=browse&gname=KPNO&gname2=KP4in#filter
- BOOTES-2:

BESSEL R: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=Generic/Bessell.R&&mode=browse&gname=Generic&gname2=Bessell#filter
SLOAN G: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=SLOAN/SDSS.g&&mode=browse&gname=SLOAN&gname2=SDSS#filter
SLOAN R: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=SLOAN/SDSS.r&&mode=browse&gname=SLOAN&gname2=SDSS#filter
SLOAN I: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=SLOAN/SDSS.i&&mode=browse&gname=SLOAN&gname2=SDSS#filter
UKIRT Z: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=UKIRT/UKIDSS.Z&&mode=browse&gname=UKIRT&gname2=UKIDSS#filter
UKIRT Y: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=UKIRT/UKIDSS.Y&&mode=browse&gname=UKIRT&gname2=UKIDSS#filter
- BOOTES-3:

SLOAN G: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=SLOAN/SDSS.g&&mode=browse&gname=SLOAN&gname2=SDSS#filter
SLOAN R: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=SLOAN/SDSS.r&&mode=browse&gname=SLOAN&gname2=SDSS#filter
SLOAN I: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=SLOAN/SDSS.i&&mode=browse&gname=SLOAN&gname2=SDSS#filter
UKIRT Z: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=UKIRT/UKIDSS.Z&&mode=browse&gname=UKIRT&gname2=UKIDSS#filterr
UKIRT Y: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=UKIRT/UKIDSS.Y&&mode=browse&gname=UKIRT&gname2=UKIDSS#filter
JOHNSON B: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=Generic/Johnson.B&&mode=browse&gname=Generic&gname2=Johnson#filter
- D50:

JOHNSON B: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=Generic/Johnson.B&&mode=browse&gname=Generic&gname2=Johnson#filter
JOHNSON V: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=Generic/Johnson.V&&mode=browse&gname=Generic&gname2=Johnson#filter
JOHNSON R: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=Generic/Johnson.R&&mode=browse&gname=Generic&gname2=Johnson#filter
JOHNSON I: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=Generic/Johnson.I&&mode=browse&gname=Generic&gname2=Johnson#filter

![09-06-2014 enlace a filtros bart](https://cloud.githubusercontent.com/assets/6812954/3223302/38ac6226-f021-11e3-9629-5311b4c3d50f.jpg)

![09-06-2014 enlace a filtros bootes-2 y 3](https://cloud.githubusercontent.com/assets/6812954/3223303/3e64fda4-f021-11e3-828b-a60e7cf5588f.jpg)

![09-06-2014 enlace a filtros d50](https://cloud.githubusercontent.com/assets/6812954/3223306/443c183e-f021-11e3-935d-7246cedc6ca0.jpg)

**Comment by angelagonzalez** [comment]
¿Por qué se ha cerrado ésta? Aún no veo el botón de características de los filtros.

**Comment by carlibiri** [comment]
Hola Fernando, se podrían poner los enlaces a los filtros en el listado de los telescopios?

**Comment by lnicastro** [comment]
That link could be added, but let me remind you that the "telescopes and instruments" DB tables will have the necessary information for the filters. With respect to the proposed table I sent last month, we can add the transmission curve, provided as a JSON string, that can be plotted/browsed with a simple JS tool. The SVO reference site could be used to feed the table. The example MySQL creation command (of course many more filters can be added):

CREATE TABLE FilterInfo (
  filter   ENUM('UNKNOWN','SDSS-U','SDSS-G','SDSS-R','SDSS-I','SDSS-Z',
           'Z_ESO846', "u'", "g'", "r'", "i'", "z'",
           'U','B','V','R','I','Z','J','Js','H','K','Ks',"K'",'Amici','Grism')
           NOT NULL,
  LAMeff   FLOAT NOT NULL DEFAULT 0 COMMENT "Effective wavelength in Angstrom",
  LAMfwhm  FLOAT NOT NULL DEFAULT 0 COMMENT "FWHM in Angstrom",
  transmission VARCHAR(8192) NOT NULL DEFAULT '' COMMENT "Transmission curve in JSON format",
  descr    VARCHAR(128) NOT NULL DEFAULT '',

  INDEX(filter)
) ENGINE=MyISAM COMMENT='GLORIA managed Filters info';

**Comment by carlibiri** [comment]
We think that, at this stage, it would be easier if we only link the filters with the information provided by Angela...

**Comment by carlibiri** [comment]
Luciano is the person who can modify the main website.

**Comment by lnicastro** [comment]
Any editor (there are 9 + 3 administrators) can edit pages.
Anyway, I can take care of the English version and ask for help for the other languages.
L.

**Comment by angelagonzalez** [comment]
Ok, done!. Thanks a lot Luciano. I close the issue.
