### ISSUE TITLE
Add a link to Aladin website so that the user can compound RGB images

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/reservations-interface#26]
This issue also comes from this one: esgg/GLORIANightExperiment#37

Add a link to Aladin website so that the user can compound RGB images (see snapshot):

http://aladin.u-strasbg.fr/

![07-06-2014 enlace a aladin](https://cloud.githubusercontent.com/assets/6812954/3209290/ace88042-ee65-11e3-9363-d75859d4a39f.jpg)

**Comment by fserena** [comment]
Hecho. He resumido un poco la frase por motivos de espacio.
Es necesario actualizar la traducción en el resto de idiomas (ni español ni inglés).

**Comment by angelagonzalez** [comment]
Ok salvo una cosa: ¿se puede poner "Aladin" en naranja o en cualquier otro color para que resalta y el usuario vea claramente que es un link "pinchable"?

**Comment by fserena** [comment]
Probé a ponerlo en naranja, pero destaca demasiado y rompe el estilo de la página. Decidí dejarlo subrayado para marcarlo como enlace...

**Comment by angelagonzalez** [comment]
¿Y un naranja pálido y cursivas? Tal y como está no resalta como link.

El criterio que se ha seguido para elementos interactivos en la main page es ponerlos en naranja, por ejemplo los enlaces a la web de filtros de los telescopios.

http://gloria-project.eu/about/telescopes-en/

**Comment by fserena** [comment]
No te preocupes, lo cambio y ya me decís.

**Comment by angelagonzalez** [comment]
Ha desaparecido el enlace a Aladin en la versión inglesa, y todo el comentario relativo a RGB en la versión española.
![17-06-2014 faltan los enlaces a aladin](https://cloud.githubusercontent.com/assets/6812954/3294309/ca8a5c2c-f5a6-11e3-8954-dbdbc1088019.jpg)

**Comment by fserena** [comment]
Creo que lo que te ha pasado es que anoche accediste desde un equipo diferente y el navegador tiene cacheada la página. Eso puede solucionarse refrescando varias veces o borrando la caché del navegador.

**Comment by angelagonzalez** [comment]
Sí, entré con un equipo diferente al igual que harán los usuarios: acceder desde distintos sitios. Lamentablemente no es por eso. Refresqué muchas veces el navegador tanto Firefox como Chrome y seguía igual. Por oro lado los usuarios no van a saber que tienen que hacer nada de esto ni por qué cada X tiempo cuando entran a Gloria dejan de funcionar ciertas cosas. Ni por qué tienen que borrar cache etc. No se puede hacer que funcione para todos los navegadores en todas las circunstancias?

**Comment by fserena** [comment]
Lógicamente, el objetivo es conseguir que todo funcione siempre bien. Pero insisto, esa página no ha cambiado desde el domingo y por eso es un problema de caché.

Borrar la caché resuelve el problema puntual, pero estoy de acuerdo en que no puede ser así siempre y para todo el mundo. Por ello, trabajamos en identificar la mejor forma de hacer que ningún navegador, en cualquiera de sus versiones, genere este tipo de incidencias. Al parecer, aún no lo hemos conseguido.

**Comment by carlibiri** [comment]
A mí me sale Ángela... Lo único es que habría que poner el marco un poco más grande porque me sale el texto recortado.

**Comment by carlibiri** [comment]
Os pongo la captura:
![image](https://cloud.githubusercontent.com/assets/7371595/3298734/d9ce43c4-f605-11e3-8998-1834bcf2ebea.png)

**Comment by fserena** [comment]
Actualizado con el color naranja oscuro y sin subrayado. Es posible que se haya solucionado el problema de caché. Ya me decís.

**Comment by angelagonzalez** [comment]
En Firefox, después de haber borrado la caché, el color del link y el formato del comentario de Aladin sale bien en todos los idiomas, por mi parte Ok.

Sin embargo, en Chrome no borré la caché y sigue sin aparecer ningún comentario en Español, y faltando el enlace a Aladin en la versión en Inglés.

Creo que llegados a este punto quizá la decisión de cerrar la issue o continuarla hasta no ser necesario borrar la caché corresponde a Carlos.

Saludos.

**Comment by angelagonzalez** [comment]
Los temas de caché continúan en:
https://github.com/GLORIA-project/night-experiment-interface/issues/22
