### ISSUE TITLE
Incluir un botón para poder reportar cuando no es posible acceder a una reserva

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/reservations-interface#27]
Añadir un botón sobre la lista de reservas a la derecha (similar al de 'Tutorials') que se llame:

'Problems accessing?'
"¿Problemas de acceso?"

y que conduzca a las siguientes "mini-encuestas":
- Inglés: https://docs.google.com/forms/d/13tCKI5t7oDvhrC7RrItZNO1e72NAJ0RQuviRbt9_C-I/edit#
- Español: https://docs.google.com/forms/d/1de0ezuaW6sRqrGpQLAb0OWzWnOr9j8tKwhMT4tO_gE0/edit#

**Comment by angelagonzalez** [comment]
¿Se ha cerrado por error?

**Comment by fserena** [comment]
Yo creo que si. La dejo abierta mientras no esté terminada.

**Comment by fserena** [comment]
Angela, ¿podrías modificar el cuestionario para que recoja también feedback del experimento solar?

**Comment by angelagonzalez** [comment]
¿Te refieres sólo a las encuestas  de cuando no pueden acceder, o a las generales?

**Comment by fserena** [comment]
El botón de encuesta (feedback) aparece siempre, pero destaca cuando una reserva tiene error.
El tema es que también puede ser que una reserva del solar tenga error, y el cuestionario está hecho sólo para el nocturno.

**Comment by angelagonzalez** [comment]
Sí, pero hay dos encuestas. La normal, que es la que sale actualmente al final de la reserva (hay versión en Inglés y en Español), y la reducida, que la hice el otro día sólo para los casos en los que no pueden acceder (en ésta no se pregunta si ha podido mover el telescopio o tomar imágenes, ya que es obvio que no ha podido acceder). Si es para el botón que va a estar siempre visible, se entiende que es para enlazarlo con las encuestas reducidas.

A las encuestas generales, en Inglés y en Español les acabi de añadir el TADs. Hago lo propio con las reducidas también. Si necesitas las rutas de las 4 (2+2) te las paso por e-mail mejor.

**Comment by fserena** [comment]
Si, hablaba de la reducida. He visto que has añadido el TADs, pero el título del cuestionario sigue hablando del nocturno.

El cuestionario al final de la reserva del solar lo pondré en lo que queda de semana.

**Comment by angelagonzalez** [comment]
Gracias por la puntualización, no me había percatado, ahora lo cambio y te mando los enlaces totales por e-mail.

**Comment by fserena** [comment]
He actualizado la página de reservas de forma que ahora siempre aparece un botón de **Feedback** a la derecha del título. Cuando el usuario hace click en una reserva en ERROR, el botón de feedback vibra para llamar la atención del usuario.

El cuestionario al que se redirige tras hacer click depende del idioma seleccionado.

**Comment by angelagonzalez** [comment]
¿Puedes hacer que se llame 'PROBLEMS ACCESSING?'? Para que el usuario lo tenga más claro...

**Comment by fserena** [comment]
Por supuesto, pero quizá es mejor considerarlo como Feedback en general, ya que el cuestionario no sólo sirve para reportar problemas. Si alguien quiere opinar acerca de la precisión de la información y no tiene problemas para acceder, creo que el botón de _problemas_ no es intuitivo.
¿Qué te parece?

**Comment by angelagonzalez** [comment]
Entiendo lo que dices y lo comparto, pero creo que hay muchos usuarios que no sabrán lo que significa la palabra 'Feedback'. es un término un poco técnico para la gente de la calle. Quizás: 'TELL US YOUR OPINION' (en dos líneas para que no sea muy largo). O cualquier otra palabra corta, pero que sea algo más sencilla de entender para un "abuelo" que 'Feedback'.

**Comment by fserena** [comment]
Tienes razón. Por favor, si se te ocurre alguna palabra corta... let me know :)

**Comment by esgg** [comment]
Visto desde fuera OPINION me parece bien :)

**Comment by angelagonzalez** [comment]
Me parece perfecto! Además vale para Español y para Inglés :)

**Comment by fserena** [comment]
He actualizado el texto del botón. Ahora pone "Opinión" en español y "Feedback" en el resto de idiomas. Creo que es más correcto poner "Feedback" en inglés, ya que ellos lo entienden mucho mejor que los españoles :)

Además, sacado de wordreference: _feedback n (opinion about [sth])_.

**Comment by angelagonzalez** [comment]
Ok, comprobado.
